# Generated by Django 5.2 on 2025-04-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_address', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_address', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('estimated_delivery', models.DateField()),
                ('tracking_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('shipment_type', models.CharField(choices=[('document', 'Belge'), ('box', 'Koli'), ('pallet', 'Palet'), ('other', 'Diğer')], max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume_m3', models.DecimalField(decimal_places=3, max_digits=6)),
                ('status', models.CharField(choices=[('preparing', 'Hazırlanıyor'), ('on_the_way', 'Yolda'), ('in_distribution', 'Dağıtımda'), ('delivered', 'Teslim Edildi'), ('not_delivered', 'Teslim Edilemedi')], default='preparing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='vehicle.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='vehicle.vehicle')),
            ],
        ),
    ]
