# Generated by Django 5.2 on 2025-04-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Hazırlanıyor'), ('on_the_way', 'Yolda'), ('in_distribution', 'Dağıtımda'), ('delivered', 'Teslim Edildi'), ('not_delivered', 'Teslim Edilemedi')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='shipment.shipment')),
            ],
        ),
    ]
